"""agregar firmas_electronicas

Revision ID: 0994674c046f
Revises: ec016d0bae85
Create Date: 2026-07-22 20:09:55.447124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0994674c046f'
down_revision: Union[str, Sequence[str], None] = 'ec016d0bae85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmas_electronicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabla', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('significado', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_nombre_firmado', sa.String(length=150), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmas_electronicas_accion'), 'firmas_electronicas', ['accion'], unique=False)
    op.create_index(op.f('ix_firmas_electronicas_fecha'), 'firmas_electronicas', ['fecha'], unique=False)
    op.create_index(op.f('ix_firmas_electronicas_id'), 'firmas_electronicas', ['id'], unique=False)
    op.create_index(op.f('ix_firmas_electronicas_registro_id'), 'firmas_electronicas', ['registro_id'], unique=False)
    op.create_index(op.f('ix_firmas_electronicas_tabla'), 'firmas_electronicas', ['tabla'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firmas_electronicas_tabla'), table_name='firmas_electronicas')
    op.drop_index(op.f('ix_firmas_electronicas_registro_id'), table_name='firmas_electronicas')
    op.drop_index(op.f('ix_firmas_electronicas_id'), table_name='firmas_electronicas')
    op.drop_index(op.f('ix_firmas_electronicas_fecha'), table_name='firmas_electronicas')
    op.drop_index(op.f('ix_firmas_electronicas_accion'), table_name='firmas_electronicas')
    op.drop_table('firmas_electronicas')
    # ### end Alembic commands ###
