"""agregar debe_cambiar_password a usuarios

Revision ID: 7a37956e9973
Revises: 8852f91cbada
Create Date: 2026-07-22 19:00:59.668052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a37956e9973'
down_revision: Union[str, Sequence[str], None] = '8852f91cbada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('debe_cambiar_password', sa.Boolean(),
                                         nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'debe_cambiar_password')
    # ### end Alembic commands ###
