"""esquema inicial

Revision ID: 8852f91cbada
Revises: 
Create Date: 2026-07-22 18:11:09.575767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8852f91cbada'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_laboratorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email_lab', sa.String(length=150), nullable=True),
    sa.Column('logo_path', sa.String(length=300), nullable=True),
    sa.Column('codigo_formato_analisis', sa.String(length=50), nullable=True),
    sa.Column('codigo_formato_verificacion', sa.String(length=50), nullable=True),
    sa.Column('codigo_formato_mantenimiento', sa.String(length=50), nullable=True),
    sa.Column('codigo_formato_baja', sa.String(length=50), nullable=True),
    sa.Column('codigo_formato_auditoria', sa.String(length=50), nullable=True),
    sa.Column('codigo_formato_ilac', sa.String(length=50), nullable=True),
    sa.Column('version_analisis', sa.String(length=10), nullable=True),
    sa.Column('version_verificacion', sa.String(length=10), nullable=True),
    sa.Column('version_mantenimiento', sa.String(length=10), nullable=True),
    sa.Column('version_baja', sa.String(length=10), nullable=True),
    sa.Column('version_auditoria', sa.String(length=10), nullable=True),
    sa.Column('version_ilac', sa.String(length=10), nullable=True),
    sa.Column('elaborado_por', sa.String(length=150), nullable=True),
    sa.Column('revisado_por', sa.String(length=150), nullable=True),
    sa.Column('aprobado_por', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_destinatario', sa.String(length=200), nullable=True),
    sa.Column('alerta_antes_30', sa.Boolean(), nullable=True),
    sa.Column('alerta_antes_15', sa.Boolean(), nullable=True),
    sa.Column('alerta_antes_7', sa.Boolean(), nullable=True),
    sa.Column('alerta_antes_1', sa.Boolean(), nullable=True),
    sa.Column('alerta_dia_0', sa.Boolean(), nullable=True),
    sa.Column('alerta_despues_1', sa.Boolean(), nullable=True),
    sa.Column('alerta_despues_7', sa.Boolean(), nullable=True),
    sa.Column('alerta_licencia', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('numero_inventario', sa.String(length=100), nullable=True),
    sa.Column('fecha_adquisicion', sa.Date(), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('foto_path', sa.String(length=300), nullable=True),
    sa.Column('manual_path', sa.String(length=300), nullable=True),
    sa.Column('estado', sa.String(length=40), nullable=True),
    sa.Column('apto_para_uso', sa.Boolean(), nullable=True),
    sa.Column('confirmacion_metrologica', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_equipos_id'), 'equipos', ['id'], unique=False)
    op.create_table('intentos_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('ultimo_intento', sa.DateTime(), nullable=True),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intentos_login_email'), 'intentos_login', ['email'], unique=True)
    op.create_index(op.f('ix_intentos_login_id'), 'intentos_login', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('historial_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado_anterior', sa.String(length=50), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=50), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_id'), 'historial_estados', ['id'], unique=False)
    op.create_table('magnitudes_equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('simbolo', sa.String(length=20), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('rango_min', sa.Float(), nullable=True),
    sa.Column('rango_max', sa.Float(), nullable=True),
    sa.Column('resolucion', sa.String(length=100), nullable=True),
    sa.Column('emp_texto', sa.String(length=200), nullable=True),
    sa.Column('emp_valor', sa.Float(), nullable=True),
    sa.Column('emp_unidad', sa.String(length=50), nullable=True),
    sa.Column('clase_exactitud', sa.String(length=50), nullable=True),
    sa.Column('tipo_instrumento', sa.String(length=30), nullable=True),
    sa.Column('umbral_alerta_pct', sa.Float(), nullable=True),
    sa.Column('umbral_fuera_pct', sa.Float(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('motivo_desactivacion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magnitudes_equipo_id'), 'magnitudes_equipo', ['id'], unique=False)
    op.create_table('mantenimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('responsable_interno', sa.String(length=150), nullable=True),
    sa.Column('empresa_externa', sa.String(length=200), nullable=True),
    sa.Column('tecnico_externo', sa.String(length=150), nullable=True),
    sa.Column('orden_trabajo', sa.String(length=100), nullable=True),
    sa.Column('fecha_programada', sa.Date(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('falla_encontrada', sa.Text(), nullable=True),
    sa.Column('trabajo_realizado', sa.Text(), nullable=True),
    sa.Column('repuestos_utilizados', sa.Text(), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('requiere_calibracion', sa.Boolean(), nullable=True),
    sa.Column('afecta_medicion', sa.Boolean(), nullable=True),
    sa.Column('observaciones_metrologicas', sa.Text(), nullable=True),
    sa.Column('archivo_path', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mantenimientos_id'), 'mantenimientos', ['id'], unique=False)
    op.create_table('planes_mantenimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('frecuencia_meses', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_mantenimiento_id'), 'planes_mantenimiento', ['id'], unique=False)
    op.create_table('calibraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magnitud_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('numero_certificado', sa.String(length=100), nullable=True),
    sa.Column('laboratorio', sa.String(length=200), nullable=True),
    sa.Column('acreditacion_laboratorio', sa.String(length=100), nullable=True),
    sa.Column('fecha_calibracion', sa.Date(), nullable=False),
    sa.Column('proxima_calibracion', sa.Date(), nullable=True),
    sa.Column('patrones_utilizados', sa.Text(), nullable=True),
    sa.Column('metodo_calibracion', sa.String(length=200), nullable=True),
    sa.Column('temperatura_ambiente', sa.Float(), nullable=True),
    sa.Column('humedad_relativa', sa.Float(), nullable=True),
    sa.Column('trazabilidad', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('certificado_path', sa.String(length=300), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('resultado', sa.String(length=30), nullable=True),
    sa.Column('grado_regresion_sel', sa.Integer(), nullable=True),
    sa.Column('metodo_analisis', sa.String(length=20), nullable=True),
    sa.Column('usar_incertidumbre', sa.Boolean(), nullable=True),
    sa.Column('metodo_periodo', sa.String(length=30), nullable=True),
    sa.Column('justificacion_periodo', sa.Text(), nullable=True),
    sa.Column('aprobado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['magnitud_id'], ['magnitudes_equipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibraciones_id'), 'calibraciones', ['id'], unique=False)
    op.create_table('config_ilac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magnitud_id', sa.Integer(), nullable=True),
    sa.Column('metodo', sa.String(length=20), nullable=True),
    sa.Column('intervalo_inicial_meses', sa.Integer(), nullable=True),
    sa.Column('intervalo_actual_meses', sa.Integer(), nullable=True),
    sa.Column('intervalo_minimo_meses', sa.Integer(), nullable=True),
    sa.Column('intervalo_maximo_meses', sa.Integer(), nullable=True),
    sa.Column('porcentaje_escalera', sa.Float(), nullable=True),
    sa.Column('horas_uso_limite', sa.Float(), nullable=True),
    sa.Column('horas_uso_acumuladas', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['magnitud_id'], ['magnitudes_equipo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('magnitud_id')
    )
    op.create_index(op.f('ix_config_ilac_id'), 'config_ilac', ['id'], unique=False)
    op.create_table('evaluaciones_riesgo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magnitud_id', sa.Integer(), nullable=False),
    sa.Column('f_incertidumbre', sa.Integer(), nullable=True),
    sa.Column('f_tipo', sa.Integer(), nullable=True),
    sa.Column('f_riesgo_emp', sa.Integer(), nullable=True),
    sa.Column('f_fabricante', sa.Integer(), nullable=True),
    sa.Column('f_deriva', sa.Integer(), nullable=True),
    sa.Column('f_uso', sa.Integer(), nullable=True),
    sa.Column('f_ambiental', sa.Integer(), nullable=True),
    sa.Column('f_magnitud', sa.Integer(), nullable=True),
    sa.Column('f_similares', sa.Integer(), nullable=True),
    sa.Column('f_comparaciones', sa.Integer(), nullable=True),
    sa.Column('f_verificaciones', sa.Integer(), nullable=True),
    sa.Column('f_transporte', sa.Integer(), nullable=True),
    sa.Column('f_personal', sa.Integer(), nullable=True),
    sa.Column('f_legal', sa.Integer(), nullable=True),
    sa.Column('intervalo_fabricante_meses', sa.Integer(), nullable=True),
    sa.Column('puntuacion_total', sa.Float(), nullable=True),
    sa.Column('intervalo_sugerido_meses', sa.Integer(), nullable=True),
    sa.Column('intervalo_adoptado_meses', sa.Integer(), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('justificacion_exceso', sa.Text(), nullable=True),
    sa.Column('evaluado_por', sa.String(length=150), nullable=True),
    sa.Column('fecha_evaluacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['magnitud_id'], ['magnitudes_equipo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('magnitud_id')
    )
    op.create_index(op.f('ix_evaluaciones_riesgo_id'), 'evaluaciones_riesgo', ['id'], unique=False)
    op.create_table('historial_alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('magnitud_id', sa.Integer(), nullable=False),
    sa.Column('tipo_alerta', sa.String(length=20), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['magnitud_id'], ['magnitudes_equipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_alertas_id'), 'historial_alertas', ['id'], unique=False)
    op.create_table('planes_verificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magnitud_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('frecuencia_meses', sa.Integer(), nullable=True),
    sa.Column('procedimiento', sa.Text(), nullable=True),
    sa.Column('patron_referencia', sa.String(length=200), nullable=True),
    sa.Column('umbral_alerta_pct', sa.Float(), nullable=True),
    sa.Column('umbral_fuera_pct', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('justificacion_no_aplica', sa.Text(), nullable=True),
    sa.Column('aprobado_por_nombre', sa.String(length=150), nullable=True),
    sa.Column('aprobado_por_cargo', sa.String(length=150), nullable=True),
    sa.Column('fecha_aprobacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['magnitud_id'], ['magnitudes_equipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_verificacion_id'), 'planes_verificacion', ['id'], unique=False)
    op.create_table('puntos_calibracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calibracion_id', sa.Integer(), nullable=False),
    sa.Column('numero_punto', sa.Integer(), nullable=False),
    sa.Column('valor_patron', sa.Float(), nullable=False),
    sa.Column('valor_indicado', sa.Float(), nullable=False),
    sa.Column('error', sa.Float(), nullable=True),
    sa.Column('tolerancia_inf', sa.Float(), nullable=True),
    sa.Column('tolerancia_sup', sa.Float(), nullable=True),
    sa.Column('incertidumbre', sa.Float(), nullable=True),
    sa.Column('abs_error_mas_u', sa.Float(), nullable=True),
    sa.Column('emp_punto', sa.Float(), nullable=True),
    sa.Column('dentro_tolerancia', sa.Boolean(), nullable=True),
    sa.Column('observacion', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['calibracion_id'], ['calibraciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puntos_calibracion_id'), 'puntos_calibracion', ['id'], unique=False)
    op.create_table('verificaciones_intermedias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('magnitud_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('proxima_verificacion', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('realizada_por', sa.String(length=150), nullable=True),
    sa.Column('patron_usado', sa.String(length=200), nullable=True),
    sa.Column('resultado', sa.String(length=30), nullable=True),
    sa.Column('accion_tomada', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('archivo_path', sa.String(length=300), nullable=True),
    sa.Column('max_desviacion_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['magnitud_id'], ['magnitudes_equipo.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['planes_verificacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verificaciones_intermedias_id'), 'verificaciones_intermedias', ['id'], unique=False)
    op.create_table('puntos_verificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verificacion_id', sa.Integer(), nullable=False),
    sa.Column('numero_punto', sa.Integer(), nullable=False),
    sa.Column('valor_patron', sa.Float(), nullable=False),
    sa.Column('valor_indicado', sa.Float(), nullable=True),
    sa.Column('error', sa.Float(), nullable=True),
    sa.Column('tolerancia_inf', sa.Float(), nullable=True),
    sa.Column('tolerancia_sup', sa.Float(), nullable=True),
    sa.Column('desviacion_pct', sa.Float(), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=True),
    sa.Column('observacion', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones_intermedias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puntos_verificacion_id'), 'puntos_verificacion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_puntos_verificacion_id'), table_name='puntos_verificacion')
    op.drop_table('puntos_verificacion')
    op.drop_index(op.f('ix_verificaciones_intermedias_id'), table_name='verificaciones_intermedias')
    op.drop_table('verificaciones_intermedias')
    op.drop_index(op.f('ix_puntos_calibracion_id'), table_name='puntos_calibracion')
    op.drop_table('puntos_calibracion')
    op.drop_index(op.f('ix_planes_verificacion_id'), table_name='planes_verificacion')
    op.drop_table('planes_verificacion')
    op.drop_index(op.f('ix_historial_alertas_id'), table_name='historial_alertas')
    op.drop_table('historial_alertas')
    op.drop_index(op.f('ix_evaluaciones_riesgo_id'), table_name='evaluaciones_riesgo')
    op.drop_table('evaluaciones_riesgo')
    op.drop_index(op.f('ix_config_ilac_id'), table_name='config_ilac')
    op.drop_table('config_ilac')
    op.drop_index(op.f('ix_calibraciones_id'), table_name='calibraciones')
    op.drop_table('calibraciones')
    op.drop_index(op.f('ix_planes_mantenimiento_id'), table_name='planes_mantenimiento')
    op.drop_table('planes_mantenimiento')
    op.drop_index(op.f('ix_mantenimientos_id'), table_name='mantenimientos')
    op.drop_table('mantenimientos')
    op.drop_index(op.f('ix_magnitudes_equipo_id'), table_name='magnitudes_equipo')
    op.drop_table('magnitudes_equipo')
    op.drop_index(op.f('ix_historial_estados_id'), table_name='historial_estados')
    op.drop_table('historial_estados')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_intentos_login_id'), table_name='intentos_login')
    op.drop_index(op.f('ix_intentos_login_email'), table_name='intentos_login')
    op.drop_table('intentos_login')
    op.drop_index(op.f('ix_equipos_id'), table_name='equipos')
    op.drop_table('equipos')
    op.drop_table('config_notificaciones')
    op.drop_table('config_laboratorio')
    # ### end Alembic commands ###
