"""bloqueo de login por email+ip y por ip global

Revision ID: 9c49db38b7c1
Revises: 0994674c046f
Create Date: 2026-07-22 21:20:33.453618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c49db38b7c1'
down_revision: Union[str, Sequence[str], None] = '0994674c046f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intentos_login_ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('ultimo_intento', sa.DateTime(), nullable=True),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intentos_login_ip_id'), 'intentos_login_ip', ['id'], unique=False)
    op.create_index(op.f('ix_intentos_login_ip_ip'), 'intentos_login_ip', ['ip'], unique=True)
    op.add_column('intentos_login', sa.Column('ip', sa.String(length=45),
                                                nullable=False, server_default=''))
    op.drop_index(op.f('ix_intentos_login_email'), table_name='intentos_login')
    op.create_index(op.f('ix_intentos_login_email'), 'intentos_login', ['email'], unique=False)
    op.create_unique_constraint('uq_intentos_login_email_ip', 'intentos_login', ['email', 'ip'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_intentos_login_email_ip', 'intentos_login', type_='unique')
    op.drop_index(op.f('ix_intentos_login_email'), table_name='intentos_login')
    op.create_index(op.f('ix_intentos_login_email'), 'intentos_login', ['email'], unique=True)
    op.drop_column('intentos_login', 'ip')
    op.drop_index(op.f('ix_intentos_login_ip_ip'), table_name='intentos_login_ip')
    op.drop_index(op.f('ix_intentos_login_ip_id'), table_name='intentos_login_ip')
    op.drop_table('intentos_login_ip')
    # ### end Alembic commands ###
