"""agregar registro_auditoria

Revision ID: d2fd896b2907
Revises: 7a37956e9973
Create Date: 2026-07-22 19:46:35.664595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fd896b2907'
down_revision: Union[str, Sequence[str], None] = '7a37956e9973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabla', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_auditoria_fecha'), 'registro_auditoria', ['fecha'], unique=False)
    op.create_index(op.f('ix_registro_auditoria_id'), 'registro_auditoria', ['id'], unique=False)
    op.create_index(op.f('ix_registro_auditoria_registro_id'), 'registro_auditoria', ['registro_id'], unique=False)
    op.create_index(op.f('ix_registro_auditoria_tabla'), 'registro_auditoria', ['tabla'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registro_auditoria_tabla'), table_name='registro_auditoria')
    op.drop_index(op.f('ix_registro_auditoria_registro_id'), table_name='registro_auditoria')
    op.drop_index(op.f('ix_registro_auditoria_id'), table_name='registro_auditoria')
    op.drop_index(op.f('ix_registro_auditoria_fecha'), table_name='registro_auditoria')
    op.drop_table('registro_auditoria')
    # ### end Alembic commands ###
