"""soft-delete en puntos de calibracion y verificacion

Revision ID: ec016d0bae85
Revises: d2fd896b2907
Create Date: 2026-07-22 19:58:35.573147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec016d0bae85'
down_revision: Union[str, Sequence[str], None] = 'd2fd896b2907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puntos_calibracion', sa.Column('eliminado', sa.Boolean(),
                                                    nullable=False, server_default=sa.text('false')))
    op.add_column('puntos_calibracion', sa.Column('eliminado_en', sa.DateTime(), nullable=True))
    op.add_column('puntos_calibracion', sa.Column('eliminado_por_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'puntos_calibracion', 'usuarios', ['eliminado_por_id'], ['id'])
    op.add_column('puntos_verificacion', sa.Column('eliminado', sa.Boolean(),
                                                     nullable=False, server_default=sa.text('false')))
    op.add_column('puntos_verificacion', sa.Column('eliminado_en', sa.DateTime(), nullable=True))
    op.add_column('puntos_verificacion', sa.Column('eliminado_por_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'puntos_verificacion', 'usuarios', ['eliminado_por_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'puntos_verificacion', type_='foreignkey')
    op.drop_column('puntos_verificacion', 'eliminado_por_id')
    op.drop_column('puntos_verificacion', 'eliminado_en')
    op.drop_column('puntos_verificacion', 'eliminado')
    op.drop_constraint(None, 'puntos_calibracion', type_='foreignkey')
    op.drop_column('puntos_calibracion', 'eliminado_por_id')
    op.drop_column('puntos_calibracion', 'eliminado_en')
    op.drop_column('puntos_calibracion', 'eliminado')
    # ### end Alembic commands ###
